### ISSUE TITLE
배포

### ISSUE THREAD

**Issue by jmkim0** [codestates-seb/seb41_main_034#47]
Docker Compose 기반으로 실행합니다.

### 사용한 컨테이너 이미지
- 웹 서버: [NGINX](https://hub.docker.com/_/nginx) (static file serving & reverse proxy)
- RDB: [MariaDB](https://hub.docker.com/_/mariadb) (MySQL 호환)
- Backend: [Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin) JRE 11 (OpenJDK)

### 필요한 파일 및 폴더 설명
- [compose.yml
](https://github.com/codestates-seb/seb41_main_034/blob/dev/compose.yml)  docker-compose 설정 파일

- nginx/[nginx.conf](https://github.com/codestates-seb/seb41_main_034/blob/dev/nginx/nginx.conf)
  nginx 설정 파일

- secrets
  secrets 폴더는 git에 추적되지 않게 하고 별도로 공유합니다.

  - db-password
    DB root 계정 비밀번호를 담은 텍스트 파일

  - backend.yml
    Spring Boot 애플리케이션 실행시 필요한 비밀 설정값(`{}`로 감싼 값)을 포함한 설정 파일
    ```yaml
    spring:
      h2:
        console:
          enabled: false
      datasource:
        url: jdbc:mysql://db/foodmeet
        username: root
        password: {MariaDB root 비밀번호}
      jpa:
        show-sql: false
        hibernate:
          ddl-auto: update
      servlet:
        multipart:
          max-file-size: 5MB

    logging:
      level:
        org:
          springframework:
            orm:
              jpa: INFO

    image:
      local-path: /images
      server-url: http://ec2-3-34-193-217.ap-northeast-2.compute.amazonaws.com/images/

    jwt:
      key: {JWT secret}
      access-token-expiration-minutes: 60
      refresh-token-expiration-minutes: 720

    account:
      admin: {관리자 계정}
    ```

- client/build
  프론트엔드 빌드 파일을 담은 폴더, git에 추적되지 않고 별도로 빌드합니다.

- server/build/lib
  백엔드 빌드 jar 파일을 담은 폴더, git에 추적되지 않고 별도로 빌드합니다.

- images
  이미지 파일을 담은 폴더, git에 추적되지 않고 백엔드 애플리케이션을 통해 이미지 파일이 저장됩니다.

### 실행 방법
```shell
# client 빌드
cd client
npm install --force
npm run build
cd ..

# server 빌드
cd server
./gradlew build
cd ..

# 이하 서버에서 실행시 sudo 필요

# docker-compose 실행
# -d 옵션: 백그라운드에서 실행
docker-compose up -d

# 실행 중인 컨테이너 확인하기
docker-compose ps

# 실행 중인 컨테이너 로그 정보 보기
# --follow 옵션: 실시간으로 로그 확인
docker-compose logs --follow

# 빌드 파일 변경 후 재시작하기
docker-compose up -d --force-recreate

# 실행 중인 컨테이너 종료하기
docker-compose kill
```
- 로컬에서도 `docker-compose`로 실행이 가능합니다.
- 현재 배포하는 서버에는 Node.js, JDK를 설치하지 않았고 빌드 자체도 서버 안에서 하면 느리기 때문에 로컬에서 빌드 후 compose.yml을 포함한 배포 파일들을 서버(AWS EC2)에 옮겨서 실행하고 있습니다. (`scp`, `rsync` 사용)
- `docker-compose`를 백그라운드로 실행하고 로그는 `logs` 명령으로 확인하면 실수로 종료하는 것을 방지할 수 있습니다.
